version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py test
    environment:
      - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitmq//
    depends_on:
      - db
      - rabbitmq

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_config:app worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitmq//
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=your_db_name
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_password

  rabbitmq:
    image: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: "redis:alpine"

