# Generated by Django 4.1.4 on 2023-08-25 15:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("midi_binary", models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
